###############
###HELPER   ###
###############
VERSION="9.7.1"
###STRING VERSION VS NUMERIC
#CHAMPION_ID_LOOKUP=[('1', 'Annie'), ('2', 'Olaf'), ('3', 'Galio'), ('4', 'Twisted Fate'), ('5', 'Xin Zhao'), ('6', 'Urgot'), ('7', 'LeBlanc'), ('8', 'Vladimir'), ('9', 'Fiddlesticks'), ('10', 'Kayle'), ('11', 'Master Yi'), ('12', 'Alistar'), ('13', 'Ryze'), ('14', 'Sion'), ('15', 'Sivir'), ('16', 'Soraka'), ('17', 'Teemo'), ('18', 'Tristana'), ('19', 'Warwick'), ('20', 'Nunu & Willump'), ('21', 'Miss Fortune'), ('22', 'Ashe'), ('23', 'Tryndamere'), ('24', 'Jax'), ('25', 'Morgana'), ('26', 'Zilean'), ('27', 'Singed'), ('28', 'Evelynn'), ('29', 'Twitch'), ('30', 'Karthus'), ('31', "Cho'Gath"), ('32', 'Amumu'), ('33', 'Rammus'), ('34', 'Anivia'), ('35', 'Shaco'), ('36', 'Dr. Mundo'), ('37', 'Sona'), ('38', 'Kassadin'), ('39', 'Irelia'), ('40', 'Janna'), ('41', 'Gangplank'), ('42', 'Corki'), ('43', 'Karma'), ('44', 'Taric'), ('45', 'Veigar'), ('48', 'Trundle'), ('50', 'Swain'), ('51', 'Caitlyn'), ('53', 'Blitzcrank'), ('54', 'Malphite'), ('55', 'Katarina'), ('56', 'Nocturne'), ('57', 'Maokai'), ('58', 'Renekton'), ('59', 'Jarvan IV'), ('60', 'Elise'), ('61', 'Orianna'), ('62', 'Wukong'), ('63', 'Brand'), ('64', 'Lee Sin'), ('67', 'Vayne'), ('68', 'Rumble'), ('69', 'Cassiopeia'), ('72', 'Skarner'), ('74', 'Heimerdinger'), ('75', 'Nasus'), ('76', 'Nidalee'), ('77', 'Udyr'), ('78', 'Poppy'), ('79', 'Gragas'), ('80', 'Pantheon'), ('81', 'Ezreal'), ('82', 'Mordekaiser'), ('83', 'Yorick'), ('84', 'Akali'), ('85', 'Kennen'), ('86', 'Garen'), ('89', 'Leona'), ('90', 'Malzahar'), ('91', 'Talon'), ('92', 'Riven'), ('96', "Kog'Maw"), ('98', 'Shen'), ('99', 'Lux'), ('101', 'Xerath'), ('102', 'Shyvana'), ('103', 'Ahri'), ('104', 'Graves'), ('105', 'Fizz'), ('106', 'Volibear'), ('107', 'Rengar'), ('110', 'Varus'), ('111', 'Nautilus'), ('112', 'Viktor'), ('113', 'Sejuani'), ('114', 'Fiora'), ('115', 'Ziggs'), ('117', 'Lulu'), ('119', 'Draven'), ('120', 'Hecarim'), ('121', "Kha'Zix"), ('122', 'Darius'), ('126', 'Jayce'), ('127', 'Lissandra'), ('131', 'Diana'), ('133', 'Quinn'), ('134', 'Syndra'), ('136', 'Aurelion Sol'), ('141', 'Kayn'), ('142', 'Zoe'), ('143', 'Zyra'), ('145', "Kai'Sa"), ('150', 'Gnar'), ('154', 'Zac'), ('157', 'Yasuo'), ('161', "Vel'Koz"), ('163', 'Taliyah'), ('164', 'Camille'), ('201', 'Braum'), ('202', 'Jhin'), ('203', 'Kindred'), ('222', 'Jinx'), ('223', 'Tahm Kench'), ('236', 'Lucian'), ('238', 'Zed'), ('240', 'Kled'), ('245', 'Ekko'), ('254', 'Vi'), ('266', 'Aatrox'), ('267', 'Nami'), ('268', 'Azir'), ('412', 'Thresh'), ('420', 'Illaoi'), ('421', "Rek'Sai"), ('427', 'Ivern'), ('429', 'Kalista'), ('432', 'Bard'), ('497', 'Rakan'), ('498', 'Xayah'), ('516', 'Ornn'), ('517', 'Sylas'), ('518', 'Neeko'), ('555', 'Pyke')]

CHAMPION_ID_LOOKUP=[(1, 'Annie'), (2, 'Olaf'), (3, 'Galio'), (4, 'Twisted Fate'), (5, 'Xin Zhao'), (6, 'Urgot'), (7, 'LeBlanc'), (8, 'Vladimir'), (9, 'Fiddlesticks'), (10, 'Kayle'), (11, 'Master Yi'), (12, 'Alistar'), (13, 'Ryze'), (14, 'Sion'), (15, 'Sivir'), (16, 'Soraka'), (17, 'Teemo'), (18, 'Tristana'), (19, 'Warwick'), (20, 'Nunu & Willump'), (21, 'Miss Fortune'), (22, 'Ashe'), (23, 'Tryndamere'), (24, 'Jax'), (25, 'Morgana'), (26, 'Zilean'), (27, 'Singed'), (28, 'Evelynn'), (29, 'Twitch'), (30, 'Karthus'), (31, "Cho'Gath"), (32, 'Amumu'), (33, 'Rammus'), (34, 'Anivia'), (35, 'Shaco'), (36, 'Dr. Mundo'), (37, 'Sona'), (38, 'Kassadin'), (39, 'Irelia'), (40, 'Janna'), (41, 'Gangplank'), (42, 'Corki'), (43, 'Karma'), (44, 'Taric'), (45, 'Veigar'), (48, 'Trundle'), (50, 'Swain'), (51, 'Caitlyn'), (53, 'Blitzcrank'), (54, 'Malphite'), (55, 'Katarina'), (56, 'Nocturne'), (57, 'Maokai'), (58, 'Renekton'), (59, 'Jarvan IV'), (60, 'Elise'), (61, 'Orianna'), (62, 'Wukong'), (63, 'Brand'), (64, 'Lee Sin'), (67, 'Vayne'), (68, 'Rumble'), (69, 'Cassiopeia'), (72, 'Skarner'), (74, 'Heimerdinger'), (75, 'Nasus'), (76, 'Nidalee'), (77, 'Udyr'), (78, 'Poppy'), (79, 'Gragas'), (80, 'Pantheon'), (81, 'Ezreal'), (82, 'Mordekaiser'), (83, 'Yorick'), (84, 'Akali'), (85, 'Kennen'), (86, 'Garen'), (89, 'Leona'), (90, 'Malzahar'), (91, 'Talon'), (92, 'Riven'), (96, "Kog'Maw"), (98, 'Shen'), (99, 'Lux'), (101, 'Xerath'), (102, 'Shyvana'), (103, 'Ahri'), (104, 'Graves'), (105, 'Fizz'), (106, 'Volibear'), (107, 'Rengar'), (110, 'Varus'), (111, 'Nautilus'), (112, 'Viktor'), (113, 'Sejuani'), (114, 'Fiora'), (115, 'Ziggs'), (117, 'Lulu'), (119, 'Draven'), (120, 'Hecarim'), (121, "Kha'Zix"), (122, 'Darius'), (126, 'Jayce'), (127, 'Lissandra'), (131, 'Diana'), (133, 'Quinn'), (134, 'Syndra'), (136, 'Aurelion Sol'), (141, 'Kayn'), (142, 'Zoe'), (143, 'Zyra'), (145, "Kai'Sa"), (150, 'Gnar'), (154, 'Zac'), (157, 'Yasuo'), (161, "Vel'Koz"), (163, 'Taliyah'), (164, 'Camille'), (201, 'Braum'), (202, 'Jhin'), (203, 'Kindred'), (222, 'Jinx'), (223, 'Tahm Kench'), (236, 'Lucian'), (238, 'Zed'), (240, 'Kled'), (245, 'Ekko'), (254, 'Vi'), (266, 'Aatrox'), (267, 'Nami'), (268, 'Azir'), (412, 'Thresh'), (420, 'Illaoi'), (421, "Rek'Sai"), (427, 'Ivern'), (429, 'Kalista'), (432, 'Bard'), (497, 'Rakan'), (498, 'Xayah'), (516, 'Ornn'), (517, 'Sylas'), (518, 'Neeko'), (555, 'Pyke')]

QUEUETYPES=[('72', 'Howling Abyss', '1v1 Snowdown Showdown games'), ('73', 'Howling Abyss', '2v2 Snowdown Showdown games'), ('75', "Summoner's Rift", '6v6 Hexakill games'), ('76', "Summoner's Rift", 'Ultra Rapid Fire games'), ('78', 'Howling Abyss', 'One For All: Mirror Mode games'), ('83', "Summoner's Rift", 'Co-op vs AI Ultra Rapid Fire games'), ('0', 'Custom games'), ('72', 'Howling Abyss', '1v1 Snowdown Showdown games'), ('73', 'Howling Abyss', '2v2 Snowdown Showdown games'), ('75', "Summoner's Rift", '6v6 Hexakill games'), ('76', "Summoner's Rift", 'Ultra Rapid Fire games'), ('78', 'Howling Abyss', 'One For All: Mirror Mode games'), ('83', "Summoner's Rift", 'Co-op vs AI Ultra Rapid Fire games'), ('98', 'Twisted Treeline', '6v6 Hexakill games'), ('100', "Butcher's Bridge", '5v5 ARAM games'), ('310', "Summoner's Rift", 'Nemesis games'), ('313', "Summoner's Rift", 'Black Market Brawlers games'), ('317', 'Crystal Scar', 'Definitely Not Dominion games'), ('325', "Summoner's Rift", 'All Random games'), ('400', "Summoner's Rift", '5v5 Draft Pick games'), ('420', "Summoner's Rift", '5v5 Ranked Solo games'), ('430', "Summoner's Rift", '5v5 Blind Pick games'), ('440', "Summoner's Rift", '5v5 Ranked Flex games'), ('450', 'Howling Abyss', '5v5 ARAM games'), ('460', 'Twisted Treeline', '3v3 Blind Pick games'), ('470', 'Twisted Treeline', '3v3 Ranked Flex games'), ('600', "Summoner's Rift", 'Blood Hunt Assassin games'), ('610', 'Cosmic Ruins', 'Dark Star: Singularity games'), ('700', "Summoner's Rift", 'Clash games'), ('800', 'Twisted Treeline', 'Co-op vs. AI Intermediate Bot games'), ('810', 'Twisted Treeline', 'Co-op vs. AI Intro Bot games'), ('820', 'Twisted Treeline', 'Co-op vs. AI Beginner Bot games'), ('830', "Summoner's Rift", 'Co-op vs. AI Intro Bot games'), ('840', "Summoner's Rift", 'Co-op vs. AI Beginner Bot games'), ('850', "Summoner's Rift", 'Co-op vs. AI Intermediate Bot games'), ('900', "Summoner's Rift", 'ARURF games'), ('910', 'Crystal Scar', 'Ascension games'), ('920', 'Howling Abyss', 'Legend of the Poro King games'), ('940', "Summoner's Rift", 'Nexus Siege games'), ('950', "Summoner's Rift", 'Doom Bots Voting games'), ('960', "Summoner's Rift", 'Doom Bots Standard games'), ('980', 'Valoran City Park', 'Star Guardian Invasion: Normal games'), ('990', 'Valoran City Park', 'Star Guardian Invasion: Onslaught games'), ('1000', 'Overcharge', 'PROJECT: Hunters games'), ('1010', "Summoner's Rift", 'Snow ARURF games'), ('1020', "Summoner's Rift", 'One for All games'), ('1030', 'Crash Site', 'Odyssey Extraction: Intro games'), ('1040', 'Crash Site', 'Odyssey Extraction: Cadet games'), ('1050', 'Crash Site', 'Odyssey Extraction: Crewmember games'), ('1060', 'Crash Site', 'Odyssey Extraction: Captain games'), ('1070', 'Crash Site', 'Odyssey Extraction: Onslaught games'), ('1200', 'Nexus Blitz', 'Nexus Blitz games')]

MAPS=[('1', "Summoner's Rift", 'Original Summer variant'), ('2', "Summoner's Rift", 'Original Autumn variant'), ('3', 'The Proving Grounds', 'Tutorial map'), ('4', 'Twisted Treeline', 'Original version'), ('8', 'The Crystal Scar', 'Dominion map'), ('10', 'Twisted Treeline', 'Current version'), ('11', "Summoner's Rift", 'Current version'), ('12', 'Howling Abyss', 'ARAM map'), ('14', "Butcher's Bridge", 'ARAM map'), ('16', 'Cosmic Ruins', 'Dark Star: Singularity map'), ('18', 'Valoran City Park', 'Star Guardian Invasion map'), ('19', 'Substructure 43', 'PROJECT: Hunters map'), ('20', 'Crash Site', 'Odyssey: Extraction map'), ('21', 'Nexus Blitz', 'Nexus Blitz map')]

SEASONS=[('0', 'PRESEASON 3'), ('1', 'SEASON 3'), ('2', 'PRESEASON 2014'), ('3', 'SEASON 2014'), ('4', 'PRESEASON 2015'), ('5', 'SEASON 2015'), ('6', 'PRESEASON 2016'), ('7', 'SEASON 2016'), ('8', 'PRESEASON 2017'), ('9', 'SEASON 2017'), ('10', 'PRESEASON 2018'), ('11', 'SEASON 2018')]

##Really stupid python code pls no report to rito
def parseStaticTable():
    file = open("constant.txt",'r')
    mapList=list()
    for line in file:
        mapInfo=tuple([field.strip() for field in line.split('\t')])
        if len(mapInfo)<4:
            mapList.append(mapInfo)
    print(mapList)
    
def championIDToName(id):
    return [x for x in CHAMPION_ID_LOOKUP if x[0]==id][0][1]

def queueTypeIdToName(id):
    return [x for x in QUEUETYPES if x[0]==id][0][1:3]


print(queueTypeIdToName('72'))
parseStaticTable()
